export enum ROLES {
  USER = 'user',
  ADMIN = 'admin',
}

export enum ACCESS_RIGHTS {
  GET_USERS = 'getUsers',
  GET_GAMES = 'getGames',
  GET_PLAYERS = 'getPlayers',
  GET_TOKENS = 'getTokens',
  GET_GAME_TOKENS = 'getGameTokens',
  GET_API_KEYS = 'getApiKeys',
  GET_MINTED_NFTS = 'getMintedNfts',
  GET_DOCS = 'getDocs',
  IMP_PLAYER = 'impersonatePlayer',
  GET_AVAILABLE_NETWORKS = 'getAvailableNetworks',

  MANAGE_USERS = 'manageUsers',
  MANAGE_GAMES = 'manageGames',
  MANAGE_PLAYERS = 'managePlayers',
  MANAGE_TOKENS = 'manageTokens',
  MANAGE_GAME_TOKENS = 'manageGameTokens',
  MANAGE_API_KEYS = 'manageApiKeys',
  MANAGE_FILES = 'manageFiles',
  MANAGE_MINTED_NFTS = 'manageMintedNfts',
}

const allRoles = {
  [ROLES.USER]: [
    ACCESS_RIGHTS.GET_GAMES,
    ACCESS_RIGHTS.GET_PLAYERS,
    ACCESS_RIGHTS.GET_TOKENS,
    ACCESS_RIGHTS.GET_GAME_TOKENS,
    ACCESS_RIGHTS.GET_API_KEYS,
    ACCESS_RIGHTS.GET_PLAYERS,
    ACCESS_RIGHTS.GET_MINTED_NFTS,

    ACCESS_RIGHTS.MANAGE_TOKENS,
    ACCESS_RIGHTS.MANAGE_GAMES,
    ACCESS_RIGHTS.MANAGE_GAME_TOKENS,
    ACCESS_RIGHTS.MANAGE_API_KEYS,
    ACCESS_RIGHTS.MANAGE_FILES,
    ACCESS_RIGHTS.MANAGE_PLAYERS,
    ACCESS_RIGHTS.MANAGE_MINTED_NFTS,
  ],
  [ROLES.ADMIN]: [
    ACCESS_RIGHTS.GET_GAMES,
    ACCESS_RIGHTS.GET_USERS,
    ACCESS_RIGHTS.GET_PLAYERS,
    ACCESS_RIGHTS.GET_TOKENS,
    ACCESS_RIGHTS.GET_API_KEYS,
    ACCESS_RIGHTS.GET_GAME_TOKENS,
    ACCESS_RIGHTS.GET_MINTED_NFTS,
    ACCESS_RIGHTS.GET_DOCS,
    ACCESS_RIGHTS.IMP_PLAYER,
    ACCESS_RIGHTS.GET_AVAILABLE_NETWORKS,

    ACCESS_RIGHTS.MANAGE_GAMES,
    ACCESS_RIGHTS.MANAGE_USERS,
    ACCESS_RIGHTS.MANAGE_PLAYERS,
    ACCESS_RIGHTS.MANAGE_TOKENS,
    ACCESS_RIGHTS.MANAGE_GAME_TOKENS,
    ACCESS_RIGHTS.MANAGE_API_KEYS,
    ACCESS_RIGHTS.MANAGE_FILES,
    ACCESS_RIGHTS.MANAGE_MINTED_NFTS,
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

export const Roles = {
  roles,
  roleRights,
};
